# Generated by Django 6.0.2 on 2026-03-03 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_date', models.DateTimeField(auto_now_add=True)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('best_vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('compared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('vehicle1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_as_first', to='vehicle.vehicle')),
                ('vehicle2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_as_second', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Comparison',
                'verbose_name_plural': 'Vehicle Comparisons',
                'ordering': ['-comparison_date'],
            },
        ),
    ]
