# Generated by Django 6.0.1 on 2026-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehiclecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='safety_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
