# Generated by Django 6.0.1 on 2026-03-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_add_safety_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
