from django.core.management.base import BaseCommand
from vehicle.models import Vehicle
from decimal import Decimal


VEHICLES = [
    {
        "brand": "Tata",
        "model": "Nexon EV",
        "variant": "Max LR",
        "price": Decimal("1850000"),
        "discount_percentage": 5,
        "offer_price": Decimal("1757500"),
        "fuel_type": "Electric",
        "transmission": "Automatic",
        "engine": "30.2 kWh Battery",
        "mileage": Decimal("0.00"),
        "seating_capacity": 5,
        "body_type": "SUV",
        "color": "Flame Red",
        "description": "India's best-selling electric SUV with 465 km range and connected car features.",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        "is_featured": True,
    },
    {
        "brand": "Hyundai",
        "model": "Creta",
        "variant": "SX Turbo",
        "price": Decimal("1650000"),
        "discount_percentage": 8,
        "offer_price": Decimal("1518000"),
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine": "1.4L Turbo GDi",
        "mileage": Decimal("16.80"),
        "seating_capacity": 5,
        "body_type": "SUV",
        "color": "Phantom Black",
        "description": "Premium compact SUV with panoramic sunroof, ADAS and connected features.",
        "image_url": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
        "is_featured": True,
    },
    {
        "brand": "Maruti Suzuki",
        "model": "Brezza",
        "variant": "ZXi Plus AT",
        "price": Decimal("1250000"),
        "discount_percentage": None,
        "offer_price": None,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine": "1.5L K15C Smart Hybrid",
        "mileage": Decimal("19.80"),
        "seating_capacity": 5,
        "body_type": "SUV",
        "color": "Sizzling Red",
        "description": "India's most reliable compact SUV with best-in-class mileage.",
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
        "is_featured": True,
    },
    {
        "brand": "Honda",
        "model": "City",
        "variant": "Hybrid ZX CVT",
        "price": Decimal("1980000"),
        "discount_percentage": 10,
        "offer_price": Decimal("1782000"),
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "engine": "1.5L i-MMD Strong Hybrid",
        "mileage": Decimal("26.50"),
        "seating_capacity": 5,
        "body_type": "Sedan",
        "color": "Lunar Silver",
        "description": "India's first strong hybrid sedan delivering exceptional efficiency.",
        "image_url": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "is_featured": True,
    },
    {
        "brand": "Kia",
        "model": "Seltos",
        "variant": "HTX Plus Diesel",
        "price": Decimal("1780000"),
        "discount_percentage": 6,
        "offer_price": Decimal("1673200"),
        "fuel_type": "Diesel",
        "transmission": "Automatic",
        "engine": "1.5L CRDi VGT",
        "mileage": Decimal("21.40"),
        "seating_capacity": 5,
        "body_type": "SUV",
        "color": "Aurora Black Pearl",
        "description": "Feature-loaded SUV with Bose sound system and 10.25\" dual screen.",
        "image_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
        "is_featured": True,
    },
    {
        "brand": "Mahindra",
        "model": "XUV700",
        "variant": "AX7 Luxury Pack",
        "price": Decimal("2490000"),
        "discount_percentage": None,
        "offer_price": None,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine": "2.0L mStallion Turbo",
        "mileage": Decimal("14.40"),
        "seating_capacity": 7,
        "body_type": "SUV",
        "color": "Napoli Black",
        "description": "India's most awarded SUV with ADAS Level 2, AdrenoX connect and 7 seats.",
        "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
        "is_featured": True,
    },
    {
        "brand": "Toyota",
        "model": "Innova HyCross",
        "variant": "GX Hybrid",
        "price": Decimal("2350000"),
        "discount_percentage": 4,
        "offer_price": Decimal("2256000"),
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "engine": "2.0L Strong Hybrid",
        "mileage": Decimal("21.10"),
        "seating_capacity": 7,
        "body_type": "MUV",
        "color": "Pearl White",
        "description": "Premium TNGA-based hybrid MPV with monocoque chassis and panoramic roof.",
        "image_url": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80",
        "is_featured": False,
    },
    {
        "brand": "Volkswagen",
        "model": "Virtus",
        "variant": "GT Plus TSI DSG",
        "price": Decimal("1650000"),
        "discount_percentage": None,
        "offer_price": None,
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine": "1.5L EVO TSI",
        "mileage": Decimal("19.40"),
        "seating_capacity": 5,
        "body_type": "Sedan",
        "color": "Curcuma Yellow",
        "description": "German-engineered performance sedan with IQ.DRIVE and Ventilated seats.",
        "image_url": "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
        "is_featured": False,
    },
    {
        "brand": "MG",
        "model": "Hector",
        "variant": "Select Sharp Pro",
        "price": Decimal("1990000"),
        "discount_percentage": 7,
        "offer_price": Decimal("1850700"),
        "fuel_type": "Petrol",
        "transmission": "Manual",
        "engine": "1.5L Turbo Petrol",
        "mileage": Decimal("15.81"),
        "seating_capacity": 5,
        "body_type": "SUV",
        "color": "Glaze Red",
        "description": "Internet SUV with 14-inch touchscreen, panoramic sunroof and i-SMART tech.",
        "image_url": "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80",
        "is_featured": False,
    },
    {
        "brand": "Skoda",
        "model": "Slavia",
        "variant": "Style TSI DSG",
        "price": Decimal("1750000"),
        "discount_percentage": 5,
        "offer_price": Decimal("1662500"),
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine": "1.5L TSI EVO",
        "mileage": Decimal("18.97"),
        "seating_capacity": 5,
        "body_type": "Sedan",
        "color": "Steel Blue",
        "description": "Czech precision meets Indian roads — segment's largest-in-class boot and sunroof.",
        "image_url": "https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&q=80",
        "is_featured": False,
    },
]


class Command(BaseCommand):
    help = 'Seed 10 sample vehicles into the database'

    def handle(self, *args, **kwargs):
        if Vehicle.objects.count() >= 10:
            self.stdout.write(self.style.WARNING('Vehicles already seeded. Skipping.'))
            return

        created = 0
        for data in VEHICLES:
            _, is_new = Vehicle.objects.get_or_create(
                brand=data['brand'],
                model=data['model'],
                variant=data.get('variant'),
                defaults=data,
            )
            if is_new:
                created += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {created} vehicles.'))
